project:
  type: book

book:
  title: "ILLUSTRATED EPONYMOUS DICTIONARY OF CYTOPATHOLOGY"
  subtitle: "v. 1.0 | Haifa, Israel"
  author: "Nik Danilov"
  date: "2026"
  chapters:
    - copyright.qmd   
    - index.qmd     # Preface
    - EpoDict_body.qmd     # The Dictionary itself (the A-Z chapters)
    - personalia.qmd  # The alphabetical Index of personalia

format:
  html:
    number-sections: false
    toc: true
    toc-depth: 2
    page-navigation: true
    chunk-level: 2 # This tells Quarto to start a new page at every ## header
    css: styles.css
    lightbox: auto
  pdf:
    number-sections: false
    toc: true
    toc-depth: 2
    page-navigation: true
    chunk-level: 2
    css: styles.css
    papersize: a4
    fontsize: 12pt
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    fig-align: center
    fig-width: 5
    fig-height: 5
  
